"""Add driver availability fields

Revision ID: 4d3b479c141d
Revises: 
Create Date: 2026-07-31 14:53:49.192846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3b479c141d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('availability_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'current_longitude')
    op.drop_column('users', 'current_latitude')
    op.drop_column('users', 'availability_status')
    # ### end Alembic commands ###
