"""Add RideGuard safety events

Revision ID: 9feaa18baff2
Revises: password_reset_tokens
Create Date: 2026-10-01 18:35:26.144335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9feaa18baff2'
down_revision: Union[str, Sequence[str], None] = 'password_reset_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_guard_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ride_guard_events_created_at', 'ride_guard_events', ['created_at'], unique=False)
    op.create_index('ix_ride_guard_events_driver_id', 'ride_guard_events', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ride_guard_events_id'), 'ride_guard_events', ['id'], unique=False)
    op.create_index('ix_ride_guard_events_ride_id', 'ride_guard_events', ['ride_id'], unique=False)
    op.create_index('ix_ride_guard_events_status', 'ride_guard_events', ['status'], unique=False)
    op.create_index('ix_ride_guard_events_type', 'ride_guard_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ride_guard_events_type', table_name='ride_guard_events')
    op.drop_index('ix_ride_guard_events_status', table_name='ride_guard_events')
    op.drop_index('ix_ride_guard_events_ride_id', table_name='ride_guard_events')
    op.drop_index(op.f('ix_ride_guard_events_id'), table_name='ride_guard_events')
    op.drop_index('ix_ride_guard_events_driver_id', table_name='ride_guard_events')
    op.drop_index('ix_ride_guard_events_created_at', table_name='ride_guard_events')
    op.drop_table('ride_guard_events')
    # ### end Alembic commands ###
